# Generated by Django 3.1.7 on 2021-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='blocker_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
